package main

import (
	"fmt"
	"net/http"
	"os"
	"regexp"
	"strings"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"

	"github.com/aqcool/protoc-gen-go-fiber/internal/pathutil"
)

const (
	contextPackage    = protogen.GoImportPath("context")
	fiberPackage        = protogen.GoImportPath("github.com/gofiber/fiber/v3")
	bindingPackage      = protogen.GoImportPath("github.com/aqcool/protoc-gen-go-fiber/binding")
	httpbodyPackage     = protogen.GoImportPath("google.golang.org/genproto/googleapis/api/httpbody")
	httpBodyFullName    = protoreflect.FullName("google.api.HttpBody")
)

var methodSets = make(map[string]int)

// generateFile 为含 HTTP 规则的服务生成 *_fiber.pb.go。
func generateFile(gen *protogen.Plugin, file *protogen.File, omitempty bool, omitemptyPrefix string) *protogen.GeneratedFile {
	if len(file.Services) == 0 || (omitempty && !hasHTTPRule(file.Services)) {
		return nil
	}
	filename := file.GeneratedFilenamePrefix + "_fiber.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-fiber. DO NOT EDIT.")
	g.P("// versions:")
	g.P(fmt.Sprintf("// - protoc-gen-go-fiber %s", release))
	g.P("// - protoc             ", protocVersion(gen))
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	generateFileContent(gen, file, g, omitempty, omitemptyPrefix)
	return g
}

func generateFileContent(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile, omitempty bool, omitemptyPrefix string) {
	if len(file.Services) == 0 {
		return
	}
	g.P("// This is a compile-time assertion to ensure that this generated file")
	g.P("// is compatible with the protoc-gen-go-fiber runtime.")
	g.P("var _ = new(", contextPackage.Ident("Context"), ")")
	g.P("var _ ", fiberPackage.Ident("Router"))
	g.P("var _ = ", bindingPackage.Ident("Ensure"))
	g.P()

	for _, service := range file.Services {
		genService(gen, file, g, service, omitempty, omitemptyPrefix)
	}
}

func genService(_ *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile, service *protogen.Service, omitempty bool, omitemptyPrefix string) {
	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		g.P("//")
		g.P(deprecationComment)
	}
	sd := &serviceDesc{
		ServiceType: service.GoName,
		ServiceName: string(service.Desc.FullName()),
		Metadata:    file.Desc.Path(),
	}
	for _, method := range service.Methods {
		rule, ok := proto.GetExtension(method.Desc.Options(), annotations.E_Http).(*annotations.HttpRule)
		if rule != nil && ok {
			for _, bind := range rule.AdditionalBindings {
				sd.Methods = append(sd.Methods, buildHTTPRule(g, service, method, bind, omitemptyPrefix))
			}
			sd.Methods = append(sd.Methods, buildHTTPRule(g, service, method, rule, omitemptyPrefix))
		} else if !omitempty && !method.Desc.IsStreamingClient() && !method.Desc.IsStreamingServer() {
			path := fmt.Sprintf("%s/%s/%s", omitemptyPrefix, service.Desc.FullName(), method.Desc.Name())
			sd.Methods = append(sd.Methods, buildMethodDesc(g, method, http.MethodPost, path))
		}
	}
	if len(sd.Methods) != 0 {
		if sd.hasHTTPBody() {
			_ = g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: httpbodyPackage, GoName: "HttpBody"})
		}
		g.P(sd.execute())
	}
}

func hasHTTPRule(services []*protogen.Service) bool {
	for _, service := range services {
		for _, method := range service.Methods {
			rule, ok := proto.GetExtension(method.Desc.Options(), annotations.E_Http).(*annotations.HttpRule)
			if rule != nil && ok {
				return true
			}
		}
	}
	return false
}

// buildHTTPRule 将单条 google.api.HttpRule 解析为 methodDesc（含 Fiber 路由与绑定元数据）。
func buildHTTPRule(g *protogen.GeneratedFile, service *protogen.Service, m *protogen.Method, rule *annotations.HttpRule, omitemptyPrefix string) *methodDesc {
	var (
		path         string
		method       string
		body         string
		responseBody string
	)

	switch pattern := rule.Pattern.(type) {
	case *annotations.HttpRule_Get:
		path = pattern.Get
		method = http.MethodGet
	case *annotations.HttpRule_Put:
		path = pattern.Put
		method = http.MethodPut
	case *annotations.HttpRule_Post:
		path = pattern.Post
		method = http.MethodPost
	case *annotations.HttpRule_Delete:
		path = pattern.Delete
		method = http.MethodDelete
	case *annotations.HttpRule_Patch:
		path = pattern.Patch
		method = http.MethodPatch
	case *annotations.HttpRule_Custom:
		path = pattern.Custom.Path
		method = pattern.Custom.Kind
	}
	if method == "" {
		method = http.MethodPost
	}
	if path == "" {
		path = fmt.Sprintf("%s/%s/%s", omitemptyPrefix, service.Desc.FullName(), m.Desc.Name())
	}
	body = rule.Body
	responseBody = rule.ResponseBody
	md := buildMethodDesc(g, m, method, path)
	if !m.Desc.IsStreamingClient() {
		if method == http.MethodGet || method == http.MethodDelete {
			if body != "" {
				_, _ = fmt.Fprintf(os.Stderr, "\u001B[31mWARN\u001B[m: %s %s body should not be declared.\n", method, path)
			}
		} else if body == "" {
			_, _ = fmt.Fprintf(os.Stderr, "\u001B[31mWARN\u001B[m: %s %s does not declare a body.\n", method, path)
		}
	}
	if body == "*" {
		md.HasBody = true
		md.Body = ""
		md.BodyField = "*"
		md.BodyHTTPBody = isHTTPBodyMessage(m.Input.Desc)
	} else if body != "" {
		fd := m.Input.Desc.Fields().ByName(protoreflect.Name(body))
		if fd == nil {
			fmt.Fprintf(os.Stderr, "\u001B[31mERROR\u001B[m: The corresponding body field '%s' declaration in request message could not be found in '%s'\n", body, path)
			os.Exit(2)
		}
		md.HasBody = true
		md.Body = "." + camelCaseVars(body)
		md.BodyField = body
		md.BodyQueryName = fd.JSONName()
		md.BodyHTTPBody = isHTTPBodyField(fd)
		md.BodyMessage = fd.Kind() == protoreflect.MessageKind && !fd.IsList() && !fd.IsMap()
	}
	if responseBody == "*" {
		md.ResponseBody = ""
	} else if responseBody != "" {
		fd := m.Output.Desc.Fields().ByName(protoreflect.Name(responseBody))
		if fd == nil {
			fmt.Fprintf(os.Stderr, "\u001B[31mERROR\u001B[m: The corresponding response_body field '%s' declaration in response message could not be found in '%s'\n", responseBody, path)
			os.Exit(2)
		}
		md.ResponseBody = "." + camelCaseVars(responseBody)
		md.ResponseBodyField = responseBody
		md.ResponseBodyHTTPBody = isHTTPBodyField(fd)
	}
	return md
}

// buildMethodDesc 构造 methodDesc，并调用 pathutil.Convert 生成 FiberPath 与 URIParams。
func buildMethodDesc(g *protogen.GeneratedFile, m *protogen.Method, method, path string) *methodDesc {
	defer func() { methodSets[m.GoName]++ }()

	pathTemplate := path
	vars := buildPathVars(path)

	for v, s := range vars {
		fields := m.Input.Desc.Fields()
		if s != nil {
			path = replacePath(v, *s, path)
		}
		for _, field := range strings.Split(v, ".") {
			if strings.TrimSpace(field) == "" {
				continue
			}
			if strings.Contains(field, ":") {
				field = strings.Split(field, ":")[0]
			}
			fd := fields.ByName(protoreflect.Name(field))
			if fd == nil {
				fmt.Fprintf(os.Stderr, "\u001B[31mERROR\u001B[m: The corresponding field '%s' declaration in message could not be found in '%s'\n", v, path)
				os.Exit(2)
			}
			if fd.IsMap() {
				fmt.Fprintf(os.Stderr, "\u001B[31mWARN\u001B[m: The field in path:'%s' shouldn't be a map.\n", v)
			} else if fd.IsList() {
				fmt.Fprintf(os.Stderr, "\u001B[31mWARN\u001B[m: The field in path:'%s' shouldn't be a list.\n", v)
			} else if fd.Kind() == protoreflect.MessageKind || fd.Kind() == protoreflect.GroupKind {
				fields = fd.Message().Fields()
			}
		}
	}

	fiberPath, uriParams := pathutil.Convert(pathTemplate)
	fiberMethod := fiberMethodName(method)

	comment := m.Comments.Leading.String() + m.Comments.Trailing.String()
	if comment != "" {
		comment = "// " + m.GoName + strings.TrimPrefix(strings.TrimSuffix(comment, "\n"), "//")
	}
	if m.Desc.Options().(*descriptorpb.MethodOptions).GetDeprecated() {
		if comment != "" {
			comment += "\n"
		}
		comment += deprecationComment
	}
	return &methodDesc{
		Name:            m.GoName,
		OriginalName:    string(m.Desc.Name()),
		Num:             methodSets[m.GoName],
		Request:         g.QualifiedGoIdent(m.Input.GoIdent),
		Reply:           g.QualifiedGoIdent(m.Output.GoIdent),
		Comment:         comment,
		Path:            path,
		PathTemplate:    pathTemplate,
		FiberPath:       fiberPath,
		FiberMethod:     fiberMethod,
		Method:          method,
		HasVars:         len(vars) > 0,
		URIParams:       uriParams,
		ReplyHTTPBody:   isHTTPBodyMessage(m.Output.Desc),
		ClientStreaming: m.Desc.IsStreamingClient(),
		ServerStreaming: m.Desc.IsStreamingServer(),
	}
}

func fiberMethodName(method string) string {
	switch method {
	case http.MethodGet:
		return "Get"
	case http.MethodPost:
		return "Post"
	case http.MethodPut:
		return "Put"
	case http.MethodDelete:
		return "Delete"
	case http.MethodPatch:
		return "Patch"
	case http.MethodHead:
		return "Head"
	case http.MethodOptions:
		return "Options"
	default:
		return "Add"
	}
}

func isHTTPBodyField(fd protoreflect.FieldDescriptor) bool {
	return fd != nil && fd.Kind() == protoreflect.MessageKind && isHTTPBodyMessage(fd.Message())
}

func isHTTPBodyMessage(md protoreflect.MessageDescriptor) bool {
	return md != nil && md.FullName() == httpBodyFullName
}

func buildPathVars(path string) (res map[string]*string) {
	if strings.HasSuffix(path, "/") {
		fmt.Fprintf(os.Stderr, "\u001B[31mWARN\u001B[m: Path %s should not end with \"/\" \n", path)
	}
	pattern := regexp.MustCompile(`(?i){([a-z.0-9_\s]*)=?([^{}]*)}`)
	matches := pattern.FindAllStringSubmatch(path, -1)
	res = make(map[string]*string, len(matches))
	for _, m := range matches {
		name := strings.TrimSpace(m[1])
		if len(name) > 1 && len(m[2]) > 0 {
			res[name] = &m[2]
		} else {
			res[name] = nil
		}
	}
	return
}

func replacePath(name string, value string, path string) string {
	pattern := regexp.MustCompile(fmt.Sprintf(`(?i){([\s]*%s\b[\s]*)=?([^{}]*)}`, name))
	idx := pattern.FindStringIndex(path)
	if len(idx) > 0 {
		path = fmt.Sprintf("%s{%s:%s}%s", path[:idx[0]], name, pathTemplateRegex(value), path[idx[1]:])
	}
	return path
}

func pathTemplateRegex(value string) string {
	segs := strings.Split(value, "/")
	for i, seg := range segs {
		switch seg {
		case "*":
			segs[i] = "[^/]+"
		case "**":
			segs[i] = ".*"
		default:
			segs[i] = regexp.QuoteMeta(seg)
		}
	}
	return strings.Join(segs, "/")
}

func camelCaseVars(s string) string {
	subs := strings.Split(s, ".")
	vars := make([]string, 0, len(subs))
	for _, sub := range subs {
		vars = append(vars, camelCase(sub))
	}
	return strings.Join(vars, ".")
}

func camelCase(s string) string {
	if s == "" {
		return ""
	}
	t := make([]byte, 0, 32)
	i := 0
	if s[0] == '_' {
		t = append(t, 'X')
		i++
	}
	for ; i < len(s); i++ {
		c := s[i]
		if c == '_' && i+1 < len(s) && isASCIILower(s[i+1]) {
			continue
		}
		if isASCIIDigit(c) {
			t = append(t, c)
			continue
		}
		if isASCIILower(c) {
			c ^= ' '
		}
		t = append(t, c)
		for i+1 < len(s) && isASCIILower(s[i+1]) {
			i++
			t = append(t, s[i])
		}
	}
	return string(t)
}

func isASCIILower(c byte) bool { return 'a' <= c && c <= 'z' }
func isASCIIDigit(c byte) bool { return '0' <= c && c <= '9' }

func protocVersion(gen *protogen.Plugin) string {
	v := gen.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

const deprecationComment = "// Deprecated: Do not use."
