// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: path/v1/path.proto

package pathv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Book                  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	mi := &file_path_v1_path_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_path_v1_path_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRequest.ProtoReflect.Descriptor instead.
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return file_path_v1_path_proto_rawDescGZIP(), []int{0}
}

func (x *GetBookRequest) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_path_v1_path_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_path_v1_path_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_path_v1_path_proto_rawDescGZIP(), []int{1}
}

func (x *ListMembersRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListMembersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []string               `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersReply) Reset() {
	*x = ListMembersReply{}
	mi := &file_path_v1_path_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersReply) ProtoMessage() {}

func (x *ListMembersReply) ProtoReflect() protoreflect.Message {
	mi := &file_path_v1_path_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersReply.ProtoReflect.Descriptor instead.
func (*ListMembersReply) Descriptor() ([]byte, []int) {
	return file_path_v1_path_proto_rawDescGZIP(), []int{2}
}

func (x *ListMembersReply) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_path_v1_path_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_path_v1_path_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_path_v1_path_proto_rawDescGZIP(), []int{3}
}

func (x *Book) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_path_v1_path_proto protoreflect.FileDescriptor

const file_path_v1_path_proto_rawDesc = "" +
	"\n" +
	"\x12path/v1/path.proto\x12\apath.v1\x1a\x1cgoogle/api/annotations.proto\"3\n" +
	"\x0eGetBookRequest\x12!\n" +
	"\x04book\x18\x01 \x01(\v2\r.path.v1.BookR\x04book\"(\n" +
	"\x12ListMembersRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x10ListMembersReply\x12\x18\n" +
	"\amembers\x18\x01 \x03(\tR\amembers\",\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title2\xba\x01\n" +
	"\x05Books\x12N\n" +
	"\aGetBook\x12\x17.path.v1.GetBookRequest\x1a\r.path.v1.Book\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/books/{book.id}\x12a\n" +
	"\vListMembers\x12\x1b.path.v1.ListMembersRequest\x1a\x19.path.v1.ListMembersReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/members/{name}BCZAgithub.com/aqcool/protoc-gen-go-fiber/testdata/api/path/v1;pathv1b\x06proto3"

var (
	file_path_v1_path_proto_rawDescOnce sync.Once
	file_path_v1_path_proto_rawDescData []byte
)

func file_path_v1_path_proto_rawDescGZIP() []byte {
	file_path_v1_path_proto_rawDescOnce.Do(func() {
		file_path_v1_path_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_path_v1_path_proto_rawDesc), len(file_path_v1_path_proto_rawDesc)))
	})
	return file_path_v1_path_proto_rawDescData
}

var file_path_v1_path_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_path_v1_path_proto_goTypes = []any{
	(*GetBookRequest)(nil),     // 0: path.v1.GetBookRequest
	(*ListMembersRequest)(nil), // 1: path.v1.ListMembersRequest
	(*ListMembersReply)(nil),   // 2: path.v1.ListMembersReply
	(*Book)(nil),               // 3: path.v1.Book
}
var file_path_v1_path_proto_depIdxs = []int32{
	3, // 0: path.v1.GetBookRequest.book:type_name -> path.v1.Book
	0, // 1: path.v1.Books.GetBook:input_type -> path.v1.GetBookRequest
	1, // 2: path.v1.Books.ListMembers:input_type -> path.v1.ListMembersRequest
	3, // 3: path.v1.Books.GetBook:output_type -> path.v1.Book
	2, // 4: path.v1.Books.ListMembers:output_type -> path.v1.ListMembersReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_path_v1_path_proto_init() }
func file_path_v1_path_proto_init() {
	if File_path_v1_path_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_path_v1_path_proto_rawDesc), len(file_path_v1_path_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_path_v1_path_proto_goTypes,
		DependencyIndexes: file_path_v1_path_proto_depIdxs,
		MessageInfos:      file_path_v1_path_proto_msgTypes,
	}.Build()
	File_path_v1_path_proto = out.File
	file_path_v1_path_proto_goTypes = nil
	file_path_v1_path_proto_depIdxs = nil
}
