// Code generated by protoc-gen-go-fiber. DO NOT EDIT.
// versions:
// - protoc-gen-go-fiber v0.1.0
// - protoc             v5.29.3
// source: path/v1/path.proto

package pathv1

import (
	context "context"
	binding "github.com/aqcool/protoc-gen-go-fiber/binding"
	v3 "github.com/gofiber/fiber/v3"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the protoc-gen-go-fiber runtime.
var _ = new(context.Context)
var _ v3.Router
var _ = binding.Ensure

const OperationBooksGetBook = "/path.v1.Books/GetBook"
const OperationBooksListMembers = "/path.v1.Books/ListMembers"

type BooksHTTPServer interface {
	GetBook(context.Context, *GetBookRequest) (*Book, error)
	ListMembers(context.Context, *ListMembersRequest) (*ListMembersReply, error)
}

func RegisterBooksHTTPServer(r v3.Router, srv BooksHTTPServer) {
	r.Get("/v1/books/:book_id", _Books_GetBook0_HTTP_Handler(srv))
	r.Get("/v1/members/:name", _Books_ListMembers0_HTTP_Handler(srv))
}

func _Books_GetBook0_HTTP_Handler(srv BooksHTTPServer) v3.Handler {
	return func(c v3.Ctx) error {
		binding.Ensure(c)
		var in GetBookRequest
		if err := c.Bind().Query(&in); err != nil {
			return err
		}
		if err := c.Bind().URI(&in); err != nil {
			return err
		}
		if err := binding.SetURIParam(&in, "book.id", c.Params("book_id")); err != nil {
			return err
		}
		out, err := srv.GetBook(c, &in)
		if err != nil {
			return err
		}
		return binding.Write(c, v3.StatusOK, out)
	}
}

func _Books_ListMembers0_HTTP_Handler(srv BooksHTTPServer) v3.Handler {
	return func(c v3.Ctx) error {
		binding.Ensure(c)
		var in ListMembersRequest
		if err := c.Bind().Query(&in); err != nil {
			return err
		}
		if err := c.Bind().URI(&in); err != nil {
			return err
		}
		out, err := srv.ListMembers(c, &in)
		if err != nil {
			return err
		}
		return binding.Write(c, v3.StatusOK, out)
	}
}

type BooksHTTPClient interface {
	GetBook(ctx context.Context, req *GetBookRequest, opts ...binding.CallOption) (*Book, error)
	ListMembers(ctx context.Context, req *ListMembersRequest, opts ...binding.CallOption) (*ListMembersReply, error)
}

type BooksHTTPClientImpl struct {
	cc *binding.HTTPClient
}

func NewBooksHTTPClient(cc *binding.HTTPClient) BooksHTTPClient {
	return &BooksHTTPClientImpl{cc: cc}
}

func (c *BooksHTTPClientImpl) GetBook(ctx context.Context, in *GetBookRequest, opts ...binding.CallOption) (*Book, error) {
	var out Book
	pattern := "/v1/books/{book.id}"
	path := binding.Path(pattern, in, binding.WithQueryParams())
	opts = append([]binding.CallOption{binding.Header("Accept", "application/json")}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BooksHTTPClientImpl) ListMembers(ctx context.Context, in *ListMembersRequest, opts ...binding.CallOption) (*ListMembersReply, error) {
	var out ListMembersReply
	pattern := "/v1/members/{name}"
	path := binding.Path(pattern, in, binding.WithQueryParams())
	opts = append([]binding.CallOption{binding.Header("Accept", "application/json")}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
