// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: helloworld/v1/helloworld.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_helloworld_v1_helloworld_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_helloworld_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_helloworld_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_helloworld_v1_helloworld_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_helloworld_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_helloworld_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UploadHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *httpbody.HttpBody     `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadHelloRequest) Reset() {
	*x = UploadHelloRequest{}
	mi := &file_helloworld_v1_helloworld_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadHelloRequest) ProtoMessage() {}

func (x *UploadHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_helloworld_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadHelloRequest.ProtoReflect.Descriptor instead.
func (*UploadHelloRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_helloworld_proto_rawDescGZIP(), []int{2}
}

func (x *UploadHelloRequest) GetBody() *httpbody.HttpBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type UploadHelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *httpbody.HttpBody     `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadHelloReply) Reset() {
	*x = UploadHelloReply{}
	mi := &file_helloworld_v1_helloworld_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadHelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadHelloReply) ProtoMessage() {}

func (x *UploadHelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_helloworld_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadHelloReply.ProtoReflect.Descriptor instead.
func (*UploadHelloReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_helloworld_proto_rawDescGZIP(), []int{3}
}

func (x *UploadHelloReply) GetBody() *httpbody.HttpBody {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_helloworld_v1_helloworld_proto protoreflect.FileDescriptor

const file_helloworld_v1_helloworld_proto_rawDesc = "" +
	"\n" +
	"\x1ehelloworld/v1/helloworld.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/httpbody.proto\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\">\n" +
	"\x12UploadHelloRequest\x12(\n" +
	"\x04body\x18\x01 \x01(\v2\x14.google.api.HttpBodyR\x04body\"<\n" +
	"\x10UploadHelloReply\x12(\n" +
	"\x04body\x18\x01 \x01(\v2\x14.google.api.HttpBodyR\x04body2\x90\x04\n" +
	"\aGreeter\x12^\n" +
	"\bSayHello\x12\x1b.helloworld.v1.HelloRequest\x1a\x19.helloworld.v1.HelloReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/helloworld/{name}\x12]\n" +
	"\vCreateHello\x12\x1b.helloworld.v1.HelloRequest\x1a\x19.helloworld.v1.HelloReply\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/helloworld\x12h\n" +
	"\tListHello\x12\x1b.helloworld.v1.HelloRequest\x1a\x19.helloworld.v1.HelloReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/helloworld/stream/{name}0\x01\x12a\n" +
	"\tChatHello\x12\x1b.helloworld.v1.HelloRequest\x1a\x19.helloworld.v1.HelloReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/helloworld/chat(\x010\x01\x12y\n" +
	"\vUploadHello\x12!.helloworld.v1.UploadHelloRequest\x1a\x1f.helloworld.v1.UploadHelloReply\"&\x82\xd3\xe4\x93\x02 :\x04bodyb\x04body\"\x12/helloworld/uploadBDZBgithub.com/aqcool/protoc-gen-go-fiber/example/api/helloworld/v1;v1b\x06proto3"

var (
	file_helloworld_v1_helloworld_proto_rawDescOnce sync.Once
	file_helloworld_v1_helloworld_proto_rawDescData []byte
)

func file_helloworld_v1_helloworld_proto_rawDescGZIP() []byte {
	file_helloworld_v1_helloworld_proto_rawDescOnce.Do(func() {
		file_helloworld_v1_helloworld_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_v1_helloworld_proto_rawDesc), len(file_helloworld_v1_helloworld_proto_rawDesc)))
	})
	return file_helloworld_v1_helloworld_proto_rawDescData
}

var file_helloworld_v1_helloworld_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_helloworld_v1_helloworld_proto_goTypes = []any{
	(*HelloRequest)(nil),       // 0: helloworld.v1.HelloRequest
	(*HelloReply)(nil),         // 1: helloworld.v1.HelloReply
	(*UploadHelloRequest)(nil), // 2: helloworld.v1.UploadHelloRequest
	(*UploadHelloReply)(nil),   // 3: helloworld.v1.UploadHelloReply
	(*httpbody.HttpBody)(nil),  // 4: google.api.HttpBody
}
var file_helloworld_v1_helloworld_proto_depIdxs = []int32{
	4, // 0: helloworld.v1.UploadHelloRequest.body:type_name -> google.api.HttpBody
	4, // 1: helloworld.v1.UploadHelloReply.body:type_name -> google.api.HttpBody
	0, // 2: helloworld.v1.Greeter.SayHello:input_type -> helloworld.v1.HelloRequest
	0, // 3: helloworld.v1.Greeter.CreateHello:input_type -> helloworld.v1.HelloRequest
	0, // 4: helloworld.v1.Greeter.ListHello:input_type -> helloworld.v1.HelloRequest
	0, // 5: helloworld.v1.Greeter.ChatHello:input_type -> helloworld.v1.HelloRequest
	2, // 6: helloworld.v1.Greeter.UploadHello:input_type -> helloworld.v1.UploadHelloRequest
	1, // 7: helloworld.v1.Greeter.SayHello:output_type -> helloworld.v1.HelloReply
	1, // 8: helloworld.v1.Greeter.CreateHello:output_type -> helloworld.v1.HelloReply
	1, // 9: helloworld.v1.Greeter.ListHello:output_type -> helloworld.v1.HelloReply
	1, // 10: helloworld.v1.Greeter.ChatHello:output_type -> helloworld.v1.HelloReply
	3, // 11: helloworld.v1.Greeter.UploadHello:output_type -> helloworld.v1.UploadHelloReply
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_helloworld_v1_helloworld_proto_init() }
func file_helloworld_v1_helloworld_proto_init() {
	if File_helloworld_v1_helloworld_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_v1_helloworld_proto_rawDesc), len(file_helloworld_v1_helloworld_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_v1_helloworld_proto_goTypes,
		DependencyIndexes: file_helloworld_v1_helloworld_proto_depIdxs,
		MessageInfos:      file_helloworld_v1_helloworld_proto_msgTypes,
	}.Build()
	File_helloworld_v1_helloworld_proto = out.File
	file_helloworld_v1_helloworld_proto_goTypes = nil
	file_helloworld_v1_helloworld_proto_depIdxs = nil
}
