// Code generated by protoc-gen-go-fiber. DO NOT EDIT.
// versions:
// - protoc-gen-go-fiber v0.1.0
// - protoc             v5.29.3
// source: helloworld/v1/helloworld.proto

package v1

import (
	context "context"
	binding "github.com/aqcool/protoc-gen-go-fiber/binding"
	v3 "github.com/gofiber/fiber/v3"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the protoc-gen-go-fiber runtime.
var _ = new(context.Context)
var _ v3.Router
var _ = binding.Ensure

const OperationGreeterChatHello = "/helloworld.v1.Greeter/ChatHello"
const OperationGreeterCreateHello = "/helloworld.v1.Greeter/CreateHello"
const OperationGreeterListHello = "/helloworld.v1.Greeter/ListHello"
const OperationGreeterSayHello = "/helloworld.v1.Greeter/SayHello"
const OperationGreeterUploadHello = "/helloworld.v1.Greeter/UploadHello"

type GreeterHTTPServer interface {
	ChatHello(Greeter_ChatHelloServer) error
	CreateHello(context.Context, *HelloRequest) (*HelloReply, error)
	ListHello(*HelloRequest, Greeter_ListHelloServer) error
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	UploadHello(context.Context, *UploadHelloRequest) (*UploadHelloReply, error)
}

func RegisterGreeterHTTPServer(r v3.Router, srv GreeterHTTPServer) {
	r.Post("/helloworld/upload", _Greeter_UploadHello0_HTTP_Handler(srv))
	r.Get("/helloworld/chat", binding.NewWebSocketHandler(func(stream *binding.WebSocketStream) error {
		return _Greeter_ChatHello0_WS_Handler(srv, stream)
	}))
	r.Post("/helloworld", _Greeter_CreateHello0_HTTP_Handler(srv))
	r.Get("/helloworld/stream/:name", binding.NewServerStream(_Greeter_ListHello0_SSE_Handler(srv)))
	r.Get("/helloworld/:name", _Greeter_SayHello0_HTTP_Handler(srv))
}

type Greeter_ChatHelloServer interface {
	Send(*HelloReply) error
	Recv() (*HelloRequest, error)
}

type Greeter_ChatHelloHTTPServer struct {
	stream *binding.ServerStream
	ws     *binding.WebSocketStream
}

func (x *Greeter_ChatHelloHTTPServer) Send(m *HelloReply) error {
	return x.ws.Send(m)
}
func (x *Greeter_ChatHelloHTTPServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ws.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

type Greeter_ListHelloServer interface {
	Send(*HelloReply) error
}

type Greeter_ListHelloHTTPServer struct {
	stream *binding.ServerStream
}

func (x *Greeter_ListHelloHTTPServer) Send(m *HelloReply) error {
	return x.stream.Send(m)
}

func _Greeter_UploadHello0_HTTP_Handler(srv GreeterHTTPServer) v3.Handler {
	return func(c v3.Ctx) error {
		binding.Ensure(c)
		var in UploadHelloRequest
		if err := binding.BindHTTPBody(c, &in, "body"); err != nil {
			return err
		}
		if err := c.Bind().Query(&in); err != nil {
			return err
		}
		out, err := srv.UploadHello(c, &in)
		if err != nil {
			return err
		}
		return binding.Write(c, v3.StatusOK, out, binding.WithField("body"), binding.WithHTTPBody())
	}
}

func _Greeter_ChatHello0_WS_Handler(srv GreeterHTTPServer, ws *binding.WebSocketStream) error {
	return srv.ChatHello(&Greeter_ChatHelloHTTPServer{ws: ws})
}

func _Greeter_CreateHello0_HTTP_Handler(srv GreeterHTTPServer) v3.Handler {
	return func(c v3.Ctx) error {
		binding.Ensure(c)
		var in HelloRequest
		if err := c.Bind().Body(&in); err != nil {
			return err
		}
		out, err := srv.CreateHello(c, &in)
		if err != nil {
			return err
		}
		return binding.Write(c, v3.StatusOK, out)
	}
}

func _Greeter_ListHello0_SSE_Handler(srv GreeterHTTPServer) func(c v3.Ctx, stream *binding.ServerStream) error {
	return func(c v3.Ctx, stream *binding.ServerStream) error {
		binding.Ensure(c)
		var in HelloRequest
		if err := c.Bind().Query(&in); err != nil {
			return err
		}
		if err := c.Bind().URI(&in); err != nil {
			return err
		}
		return srv.ListHello(&in, &Greeter_ListHelloHTTPServer{stream: stream})
	}
}

func _Greeter_SayHello0_HTTP_Handler(srv GreeterHTTPServer) v3.Handler {
	return func(c v3.Ctx) error {
		binding.Ensure(c)
		var in HelloRequest
		if err := c.Bind().Query(&in); err != nil {
			return err
		}
		if err := c.Bind().URI(&in); err != nil {
			return err
		}
		out, err := srv.SayHello(c, &in)
		if err != nil {
			return err
		}
		return binding.Write(c, v3.StatusOK, out)
	}
}

type GreeterHTTPClient interface {
	ChatHello(ctx context.Context, opts ...binding.CallOption) (Greeter_ChatHelloClient, error)
	CreateHello(ctx context.Context, req *HelloRequest, opts ...binding.CallOption) (*HelloReply, error)
	ListHello(ctx context.Context, req *HelloRequest, opts ...binding.CallOption) (Greeter_ListHelloClient, error)
	SayHello(ctx context.Context, req *HelloRequest, opts ...binding.CallOption) (*HelloReply, error)
	UploadHello(ctx context.Context, req *UploadHelloRequest, opts ...binding.CallOption) (*UploadHelloReply, error)
}

type GreeterHTTPClientImpl struct {
	cc *binding.HTTPClient
}

func NewGreeterHTTPClient(cc *binding.HTTPClient) GreeterHTTPClient {
	return &GreeterHTTPClientImpl{cc: cc}
}

type Greeter_ChatHelloClient interface {
	Recv() (*HelloReply, error)
	Send(*HelloRequest) error
	CloseSend() error
	Close() error
}

type Greeter_ChatHelloHTTPClient struct {
	stream *binding.WSClientStream
}

type Greeter_ListHelloClient interface {
	Recv() (*HelloReply, error)
	Close() error
}

type Greeter_ListHelloHTTPClient struct {
	stream *binding.ClientStream
}

func (c *GreeterHTTPClientImpl) ChatHello(ctx context.Context, opts ...binding.CallOption) (Greeter_ChatHelloClient, error) {
	pattern := "/helloworld/chat"
	path := binding.Path(pattern, nil, binding.WithQueryParams())
	stream, err := c.cc.WebSocket(ctx, path, opts...)
	if err != nil {
		return nil, err
	}
	return &Greeter_ChatHelloHTTPClient{stream: stream}, nil
}

func (x *Greeter_ChatHelloHTTPClient) Send(m *HelloRequest) error {
	return x.stream.Send(m)
}

func (x *Greeter_ChatHelloHTTPClient) CloseSend() error {
	return nil
}

func (x *Greeter_ChatHelloHTTPClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *Greeter_ChatHelloHTTPClient) CloseAndRecv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	_ = x.stream.Close()
	return m, nil
}

func (x *Greeter_ChatHelloHTTPClient) Close() error {
	if x.stream == nil {
		return nil
	}
	return x.stream.Close()
}

func (c *GreeterHTTPClientImpl) CreateHello(ctx context.Context, in *HelloRequest, opts ...binding.CallOption) (*HelloReply, error) {
	var out HelloReply
	pattern := "/helloworld"
	path := binding.Path(pattern, in)
	opts = append([]binding.CallOption{
		binding.Header("Accept", "application/json"),
		binding.Header("Content-Type", "application/json"),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) ListHello(ctx context.Context, in *HelloRequest, opts ...binding.CallOption) (Greeter_ListHelloClient, error) {
	pattern := "/helloworld/stream/{name}"
	path := binding.Path(pattern, in, binding.WithQueryParams())
	stream, err := c.cc.ServerSentEvent(ctx, "GET", path, nil, opts...)
	if err != nil {
		return nil, err
	}
	return &Greeter_ListHelloHTTPClient{stream: stream}, nil
}

func (x *Greeter_ListHelloHTTPClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *Greeter_ListHelloHTTPClient) Close() error {
	if x.stream == nil {
		return nil
	}
	return x.stream.Close()
}

func (c *GreeterHTTPClientImpl) SayHello(ctx context.Context, in *HelloRequest, opts ...binding.CallOption) (*HelloReply, error) {
	var out HelloReply
	pattern := "/helloworld/{name}"
	path := binding.Path(pattern, in, binding.WithQueryParams())
	opts = append([]binding.CallOption{binding.Header("Accept", "application/json")}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) UploadHello(ctx context.Context, in *UploadHelloRequest, opts ...binding.CallOption) (*UploadHelloReply, error) {
	var out UploadHelloReply
	pattern := "/helloworld/upload"
	path := binding.Path(pattern, in, binding.WithQueryParams(), binding.WithOmitFields("body"))
	opts = append([]binding.CallOption{
		binding.Header("Accept", "application/json"),
		binding.Header("Content-Type", binding.BodyContentType(in.Body)),
	}, opts...)
	if out.Body == nil {
		out.Body = &httpbody.HttpBody{}
	}
	err := c.cc.Invoke(ctx, "POST", path, in.Body, out.Body, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
